# Generated by Django 4.1.5 on 2023-01-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_alter_computer_quantity_alter_computer_unit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerbrand',
            name='logo',
            field=models.ImageField(upload_to='computer/images'),
        ),
    ]
