# Generated by Django 4.1.5 on 2023-01-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0008_alter_computerbrand_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerspecification',
            old_name='brand',
            new_name='computer_brand',
        ),
    ]
