# Generated by Django 4.1.5 on 2023-01-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0009_rename_brand_computerspecification_computer_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='computer',
            new_name='computer_specification',
        ),
    ]
