# Generated by Django 4.1.5 on 2023-01-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0010_rename_computer_computer_computer_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='computer_specification',
            new_name='computer',
        ),
        migrations.RenameField(
            model_name='computerspecification',
            old_name='computer_brand',
            new_name='brand',
        ),
    ]
